apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-bite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-bite-app
  template:
    metadata:
      labels:
        app: local-bite-app
    spec:
      containers:
      - name: local-bite-app
        image: rajatsahoo/local-bite-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: local-bite-secret
              key: MONGO_URI
        - name: PORT
          value: "5000"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: local-bite-secret
              key: JWT_SECRET


